project_management/customer/urls.py
"""
    Customer urls
"""
from django.conf.urls.defaults import url, patterns

uuid_regex = '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
urlpatterns = patterns('project_management.customer',
    (r'^$', 'views.list_customer'),
    (r'^list/', 'views.clientlist'),
    (r'^create/', 'views.manage_client'),
    (r'^update/(?P<id>\d+)/$', 'views.manage_client'),
    (r'^deactivate/$', 'views.manage_client_status',
                {'is_active': False}, "deactivate-client"),
    (r'^activate/$', 'views.manage_client_status',
                {'is_active': True}, "activate-client"),
    #url(r'^create/$', 'views.manage_customer_from_project', name="create_customer"),
    #url(r'^update/(?P<id>\d+)/$', 'views.manage_customer_from_project',
                                     #name="update_customer"),
    url(r'^contact/create/$', 'views.manage_customer_contact_from_project',
                                     name="create_customer_contact"),
    url(r'^contact/update/(?P<id>\d+)/$', 'views.manage_customer_contact_from_project',
                                     name="update_customer_contact")
#    (r'^delete/(?P<id>%s)/$'%(uuid_regex), 'views.delete_customer'),
)

project_management/tasks/urls.py
"""
    Url for the task application
"""
from django.conf.urls.defaults import patterns

urlpatterns = patterns('project_management.tasks',
    (r'^$', 'views.manage_task'),
    (r'^save/$', 'views.manage_task'),
    (r'^(?P<tid>\d+)/$', 'views.manage_task'),
    (r'^list/$', 'views.task_list'),
    (r'^list/(?P<page>\d+)/$', 'views.task_list'),
    (r'^create_type/$', 'views.manage_type'),
    (r'^manage_type/(?P<id>\d+)/$', 'views.manage_type'),
    (r'^delete_type/(?P<id>\d+)/$', 'views.delete_task_type'),
    (r'^getsubtype/$', 'views.get_sub_type'),
    (r'^delete/$', 'views.delete_task',
        { 'is_project_task': True }, "project-task-delete"),
    (r'^nonproject/delete/$', 'views.delete_task',
        { 'is_project_task': False }, "non-project-task-delete"),
    (r'^nonproject/create/$', 'views.manage_non_project_task'),
    (r'^nonproject/update/(?P<id>\d+)/$', 'views.manage_non_project_task'),
    (r'^nonproject/list/$', 'views.non_project_task_list'),
)

project_management/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import list_detail
from django.views.generic.simple import direct_to_template, redirect_to

from project_management.users.models import UserProfile
from project_management.users.views import login

from project_management.projectbudget.models import *
from project_management.projectbudget.budgetmasters import *

import os.path
import django_cron

admin.autodiscover()

try:
    django_cron.autodiscover()
except:
    pass

# for the calender(datepicker) widget
urlpatterns = patterns('', (r'^jsi18n/$',
    'project_management.i18nDate.javascript_catalog',
    {'packages': 'django.conf'}),)

js_info_dict = { 'packages': ('cui.translations',), }

urlpatterns += patterns('', (r'^django-jsi18n/$',
    'django.views.i18n.javascript_catalog', js_info_dict), )

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^login/$', login, {'template_name': 'login.html'}),
    (r'^comingsoon/$', direct_to_template, {'template': 'coming_soon.html'}),
    (r'^recentupdates/$',direct_to_template, {'template': 'Recent_updates.html'}),
    (r'^re-use/$', direct_to_template, {'template': 're-use.html'}),
    (r'^re-use/components/$', direct_to_template, {'template': 'Re-Use_Library.html'}),
    (r'^5GPal/$', direct_to_template, {'template': '5G-Pal.html'}),
    (r'^5GPal/Policies/$', direct_to_template, {'template': '5gpal_Policies.html'}),
    (r'^5GPal/FxCop_and_Rules/$', direct_to_template, {'template': '5gpal_FxCop_and_Rules.html'}),
    (r'^5GPal/Process-templates/$', direct_to_template, {'template': '5gpal__process-templates.html'}),
    (r'^Mindshare/', redirect_to, {'url': '/login/'}),
    (r'^logout/$', logout, {'template_name': 'logout.html'}),
    (r'^contacts/$', login_required(list_detail.object_list),
        {'queryset':UserProfile.objects.exclude(user__is_active = False).exclude(
        user__is_staff = True).order_by('user__username'),
        'template_name': 'contacts.html'}),
)

# to load the static data
#if settings.DEBUG:
urlpatterns += patterns('', (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': os.path.join(settings.PROJECT_ROOT, "media")}),)

urlpatterns += patterns('project_management.logs',
    (r'^Logs/', 'views.DisplayLog'),
    (r'^admin.ShowLog/', 'views.DisplayLogData'),
    (r'^GetLogDetail/', 'views.GetLog'),
)

urlpatterns += patterns('',
    (r'^user/', include('project_management.users.urls')),
    (r'^project/', include('project_management.projects.urls')),
    (r'^projectbudget/', include('project_management.projectbudget.urls')),
    (r'^alert/', include('project_management.alert.urls')),
    (r'^customer/', include('project_management.customer.urls')),
    (r'^task/', include('project_management.tasks.urls')),
    (r'^milestone/', include('project_management.milestone.urls')),
    (r'^businessunit/', include('project_management.business_unit.urls')),
    (r'^event/', include('project_management.notifications.urls')),
    (r'^announcement/', include('announcements.urls')),

    # (r'^client_visit_report/', include('project_management.client_visit_report.urls')),
    
    (r'^timesheet/', include('project_management.timesheet.urls')),
    (r'^timesheetnew/', include('project_management.timesheetnew.urls')),
    (r'^NewsLetter/', include('newsletter.urls')),
    (r'^conferenceroombooking/', include('project_management.conferenceroombooking.urls')),
    (r'^codereview/', include('project_management.code_review.urls', namespace="codereview")),
    #(r'^library/',include('project_management.library.urls')),
)

urlpatterns += patterns('project_management.notifications',
    (r'^MonthlyCalendar/$', 'eventviews.MonthlyCalendar'),
    (r'^WeeklyCalendar/$', 'eventviews.WeeklyCalendar'),
    (r'^DayCalendar/$', 'eventviews.DayCalendar'),
    (r'^previousyear/(?P<type>\w+)/', 'eventviews.previousyear'),
    (r'^nextyear/(?P<type>\w+)/', 'eventviews.nextyear'),
    (r'^previousmonth/', 'eventviews.previousmonth'),
    (r'^nextmonth/', 'eventviews.nextmonth'),
    (r'^nextday/', 'eventviews.nextday'),
    (r'^previousday/', 'eventviews.previousday'),
    (r'^nextweek/', 'eventviews.nextweek'),
    (r'^previousweek/', 'eventviews.previousweek'),
    (r'^Event/', 'eventviews.Events'),
    (r'^CreateEvent/', 'eventviews.Events'),
    (r'^SaveEvent/', 'eventviews.saveEvent'),
    (r'^Eventdelete/', 'eventviews.eventDelete'),
    (r'^UpdateEvent/', 'eventviews.updateEvent'),
    (r'^EventAccess/', 'eventviews.accessEvent'),
    (r'^GetStage/', 'eventviews.getStage'),
)

#  Program Task (Internal Tab) URL's
urlpatterns += patterns('project_management.projects',
    url(r'^prog_task_in_pg/$', direct_to_template, {"template": "prog_task_in_pg.html"}, name="prog_task_in_pg"),
    #(r'^UpdateProgramTask/', 'ProgTaskListsViews.program_task_update_pg'),
    #(r'^CreateProgramTask/', 'ProgTaskListsViews.createprogramtask'),
    #(r'^CreateContinueProgramTask/', 'ProgTaskListsViews.createandcontinueprogramtask'),
    #(r'^prog_task_up/', 'ProgTaskListsViews.program_task_update'),
)

urlpatterns += patterns('project_management.repository',
    (r'^repository/', 'views.RepositoryView'),
    (r'^repositoryUpload/', 'views.RepositoryUpload'),
)

urlpatterns += patterns('project_management.non_project_task',
    #(r'^CreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskView'),
    #(r'^GetProjectTasklists/', 'createMenuTaskViews.GetTasklists'),
    #(r'^GetProjectTasklistsResources/','createMenuTaskViews.GetTasklistsResources'),
    #(r'^SaveCreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskSave'),
    #(r'^SaveAndContinueCreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskSaveAndContinue'),
)

urlpatterns += patterns('project_management.non_project_task.views',
    #(r'^NonProjectTaskList/', 'NonProjectTaskList'),
    #(r'^CreateNonProjectTask/', 'NonProjectTaskView'),
    #(r'^UpdateNonProjectTask/', 'NonProjectTaskView'),
    (r'^SaveNonProjectTask/', 'SaveNonProjectTask'),
    (r'^SaveAndContinueNonProjectTask/', 'SaveAndContinueNonProjectTask'),
    #(r'^NonProjectTaskdelete/', 'NonProjectTaskDelete'),
)

urlpatterns += patterns('project_management.Utility',
    (r'^GetPopUpDetails/', 'getPopUpDetails'),
)

urlpatterns += patterns('project_management.common_manager.views',
    (r'^MasterView/', 'MasterView'),
    (r'^MasterSave/', 'MasterSave'),
    (r'^MasterDelete/','MasterDelete'),
)

#urlpatterns = patterns('project_management.projectbudget.views',
 #                      (r'^projectbudget/$', 'projectbudget.views.cost'),
  #                    )

project_management/users/urls.py
"""
    urls required the user application.
"""

from django.conf.urls.defaults import patterns
from django.views.generic.simple import direct_to_template, redirect_to

urlpatterns = patterns('project_management.users',
    (r'^create/$', 'views.manage_user'),
    (r'^update/(?P<pid>\d+)/$', 'views.manage_user'),
    (r'^list/$', 'views.user_list'),
    (r'^deactivate/$', 'views.manage_user_status',
                {'status': False}, "deactivate-user"),
    (r'^activate/$', 'views.manage_user_status',
                {'status': True}, "activate-user"),
    (r'^myprofile/$', 'views.manage_myprofile'),
    
)

project_management/announcements/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from datetime import datetime

class Announcement(models.Model):
    announcement_ID = models.AutoField(primary_key = True)
    title = models.CharField(max_length = 120)
    content = models.TextField(blank=True, null=True)
    creation_date = models.DateTimeField(null = True,  blank = True,
                                                default=datetime.now)
    approved_by = models.ForeignKey(User, 
        related_name = '%s(class)s_approved_by', null = True )
    is_approved = models.BooleanField(default = False)
    is_rejected = models.BooleanField(default = False)
    requested_by = models.ForeignKey(User,
        related_name = '%s(class)s_requested_by', null = True)

    def __unicode__(self):
        return self.title

project_management/business_unit/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from project_management.address.models import Address

class BusinessUnitType(models.Model):
    name =  models.CharField(_('Name'), max_length = 120 )

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Business Unit Type')
        verbose_name_plural = _('Business Unit Types')
        ordering = ['name']

class BusinessUnit(models.Model):
    name = models.CharField(_('Name'), max_length = 120)
    firstname = models.CharField(_('FirstName'), max_length = 50)
    lastname =  models.CharField(_('LastName'), max_length = 50, null = True, blank = True)
    type = models.ForeignKey(BusinessUnitType, verbose_name = _('Type'))
    address = models.ForeignKey(Address, verbose_name = _('Address'),
                                                null=True, blank=True)
    related_to = models.ForeignKey('self', null = True,  blank = True,
                                                verbose_name = _('Business Unit'))
    url = models.CharField( _('Url'), max_length = 120, null = True,  blank = True)
    cancel = models.BooleanField(_('Cancel'), default = False)
    customer_code = models.CharField(_('Code'), max_length = 20 , null = True, blank = True)
    contact_email = models.EmailField(_('Email'), null = True, blank = True)
    notes = models.TextField(_('Notes'), null = True,  blank = True )
    is_active = models.BooleanField(default = True)
    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            if BusinessUnit.objects.aggregate( models.Max('id'))['id__max'] != None:
                self.customer_code = BusinessUnit.objects.aggregate(
                        models.Max('id'))['id__max']+1
            else:
                self.customer_code = 1
            print  self.customer_code
            self.customer_code = 'C00' + str(self.customer_code)
            print self.customer_code
            
        super(BusinessUnit, self).save(**kwargs)
        
    class Meta:
        verbose_name = _('Business Unit')
        verbose_name_plural = _('Business Units')
        ordering = ['name']
        
    

project_management/milestone/models.py
"""
    Milestone Models
"""

from django.db import models
from django.utils.translation import ugettext_lazy as _

class InvoiceTerms(models.Model):
    """
        Represents the invoice terms of the project
    """
    name = models.CharField(max_length = 120)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('Invoice Term')
        verbose_name_plural = _('Invoice Terms')

class Milestone(models.Model):
    """
        Represents the milestones related to the project
    """
    INVOICE = 'invoice'
    ENGINEERING = 'engineering'
    category_choices = ((INVOICE, 'invoice'), (ENGINEERING, 'engineering'))
    name = models.CharField(max_length = 120, verbose_name = _('milestone'))
    percentage = models.CharField(max_length= 10, null = True,
                    blank = True, verbose_name = _('percentage'))
    start_date = models.DateField(_('Invoice Start Date'), null = True,
                    blank = True)# Just start date.
    end_date = models.DateField(_('Invoice End Date'), null = True,
                    blank = True)
    invoice_terms = models.ForeignKey(InvoiceTerms, blank = True, null = True,
                                      verbose_name = _('Invoice Terms'))
    category = models.CharField(max_length = 16, choices = category_choices,
                                default = category_choices[0][0]) #TODO Replace with invoice.
    notes = models.TextField(null = True, blank = True, verbose_name=_('Notes'))
    cancel = models.BooleanField(default = False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('Milestone')
        verbose_name_plural = _('Milestones')

project_management/non_project_task/models.py
"""
    Non project task models.
"""

from django.db import models
from django.contrib.auth.models import User

from project_management.tasks.models import Type
from django.utils.translation import ugettext_lazy as _
#from project_management.users.models import FiveGUser


class NonProjectTask(models.Model):
    non_project_taskID = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 120)
    plannedStartDate = models.DateField(null = True,  blank = True)
    plannedEndDate = models.DateField(null = True,  blank = True)
    notes = models.TextField(null = True, blank = True)
    owner = models.ForeignKey(User)
    cancel = models.BooleanField(default = 'False')
    taskType = models.ForeignKey(Type)

    def __unicode__(self):
        return self.name

    def get_program(self):
        """
            This type of task has no project. Always return None.
        """
        return None

class NonProjectTaskAssignees(models.Model):
    non_project_taskID = models.ForeignKey(NonProjectTask)
    actualstartDate = models.DateField(null = True,  blank = True)
    actualendDate = models.DateField(null = True,  blank = True)
    user = models.ForeignKey(User)
    status = models.CharField(max_length = 50, default = 'Incomplete')

    def __unicode__(self):
        return self.non_project_taskID.name

    class Meta:
        verbose_name = _('Non project Task Assignee')
        verbose_name_plural = _('Non Project Task Assignees')

project_management/business_unit/forms.py
"""
    Business Unit forms
"""
from django import forms

from project_management.business_unit.models import BusinessUnit, \
                                                BusinessUnitType

class BusinessUnitForm(forms.ModelForm):
    """
        form which represents the business unit.
    """
    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['type'].queryset = BusinessUnitType.objects.exclude(name
                                                                = 'Customer')

    def save(self, address, commit = True):
        business_unit = super(BusinessUnitForm, self).save(commit = False)
        business_unit.address = address
        business_unit.related_to = BusinessUnit.objects.get(pk = '1')
        if commit:
            business_unit.save()
        return business_unit

    class Meta:
        model = BusinessUnit
        exclude = ('cancel', 'address', 'related_to', 'customer_code', 'firstname', 'lastname', 'contact_email', 'is_active')

project_management/templates/CreateAnnouncement.html
{% extends "base.html" %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
    <script language="javascript" type="application/javascript" src="/static/js/tiny_mce/tiny_mce.js"></script>
{% endblock %}
{% block title %} Announcement {% endblock %}
{% block programcontent %} {% endblock %}
{% block programmenu %} {% endblock %}
{% block taskmenus %} {% endblock %}
{% block contentdata %}
<script language="javascript" type="application/javascript">
	tinyMCE.init({
// General options
mode : "textareas",
theme : "advanced",
plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager",

// Theme options
theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
theme_advanced_toolbar_location : "top",
theme_advanced_toolbar_align : "left",
theme_advanced_statusbar_location : "bottom",
theme_advanced_resizing : true,
// Example content CSS (should be your site CSS)
 content_css : "css/base.css",
// Drop lists for link/image/media/template dialogs
template_external_list_url : "js/template_list.js",
external_link_list_url : "js/link_list.js",
external_image_list_url : "js/image_list.js",
media_external_list_url : "js/media_list.js",

// Replace values for the template plugin
template_replace_values : {
username : "Some User",
staffid : "991234"
}
});

function setaction(action)
{
	var formObj = document.getElementById("saveAnnouncement");
	var newAttr = document.createAttribute("action");
	
	newAttr.nodeValue = action;	
	formObj.removeAttributeNode(formObj.getAttributeNode("action"));
	formObj.setAttributeNode(newAttr);
}

function setFormAction(action){    
 if (ReqValidate('announcementname','Announcement title')) {
		var tex = $('#announcementcontent_ifr').contents().find('#tinymce>p').html();
		if(tex == '<br mce_bogus="1">'){
				alert('Announcement content cannot be empty');
				return false;			
			}
		else{
				setaction(action);
				return true;
			}
 }
 else{
 		return false;
 	  } 	
}

$(document).ready(function(){
    $('#id_requestedby').attr('readonly', 'true');
	
	if ($('#announcementID').val() == "")
		$('#id_approved_by').val('31');
	
    
});
</script>

<form id="saveAnnouncement" name="saveAnnouncement" method="post" action=".">
<table width="50%">

<tr><td class="con-red" style="padding-left:200px;" colspan="2">{{msg}}</td></tr>
<tr>
	<td style="padding-left:15px;">
		<label class="con-grey">Requested by &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		
		<input type="text" id="id_requested_by" name="id_requested_by"  maxlength="120"
		{% if mode == "update" %}
			value="{{announcement.requested_by}}"
		{% else %}
			value="{{requested_by}}"
		{% endif %}>
		
		<input type="hidden" id="hdn_id_requested_by" name="hdn_id_requested_by" value="{{requested_by.pk}}" maxlength="120"/>
 </td>
	</td>
</tr>

<tr>
<td style="padding-left:15px;">
<input type="hidden" id="announcementID" name="announcementID" value="{{announcement.pk}}"/>
<input type="hidden" id="mode" name="mode" value="{{mode}}"/>
<input type="hidden" id="announcementdate" name="announcementdate" value="{{announcement.creation_date}}"/>

<label class="con-grey">Announcement title *&nbsp;&nbsp;&nbsp;</label>
<input type="text" id="announcementname" name="announcementname" value="{{announcement.title}}" maxlength="120"/>
 </td>

 <td align="right">

{% if login_user == announcement.approved_by and mode == "update" %}
	
		<input name="Approve" type="submit" id="Approve" value="Approve" class="b1" onclick="return setFormAction('/announcement/approve/?ids={{announcement.announcement_ID}}');" />
		<input name="Reject" type="submit" id="Reject" value="Reject" class="b1" onclick="return setFormAction('/announcement/approve/?ids={{announcement.announcement_ID}}');" />
		<!--<input name="Reject" type="submit" id="Reject" value="Reject" class="b1" onclick="return setRedirection('/announcement/delete/?ids={{announcement.announcement_ID}}');" />-->
		
 
 
	
 {% else %}

 <input name="save" type="submit" id="save" value="Save" class="b1" onclick="return setFormAction('/announcement/save/');" />
 
 {% endif %}
<input name="cancel" type="submit" id="cancel" value="Cancel" class="b1" onclick="setaction('/announcement/list/');" />
 </td>
</tr>
<tr><td style="padding-left:15px;" colspan="2">
<textarea id="announcementcontent" name="announcementcontent" width="20%">
{% if announcement %} {{announcement.content}} {% endif %}
</textarea>
</td></tr>
<tr>
<td colspan="2" style="padding-left:15px;">
<span class="con-s-grey">Marked (*) Fields are Mandatory</span></td>
</tr>
<tr>
	<td colspan="2" style="padding-left:15px;">
	</td>
</tr>
<tr>
	<td colspan="2" style="padding-left:15px;">
	</td>
</tr>
<tr>
		<td style="padding-left:15px;" colspan="2"><label class="con-grey">Requested To</label>
		<select id="id_approved_by" name="id_approved_by"> 
		{% for each in approved_by %}
		
		<option style="width:60px" value="{{each.pk}}"
				{% ifequal announcement.approved_by.pk each.pk %}
				selected="selected" {% endifequal %}> {{each.username}}</option>
		{% endfor %}
		</select>
		</td>

		
</tr>
</table>
</form>
{% endblock %}

project_management/templates/project_home.html
{% extends "base.html" %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}

{% block contentdata %}
<style>
    form {padding: 10px;}
    .project-details { width: 60%; height: 100px;float: left; }
    .project-resources {width: 40%; height: 100px; float:left; }
</style>
<form id="project_home" name="project_home" action="" method="POST">
    {% include 'project_menus.html' %}
    <div class="project-details">
        
    </div>
    <div class="project-resources">
    </div>
<form>
{% endblock %}

project_management/templates/project_menus.html
{% comment %} templates that contain program menus {% endcomment %}
<style>
    div.project { min-width:50%;}
    div.project p {line-height: 80%;}
    div.project P:first-letter { font-weight: bold; float:left; font-size: 360%;  }
    div.project P:first-line { font-weight: bold; float:left; font-size: 110%; }
</style>
	
<div class="project-info">
    <div>
	<br>
        <div class="project"><p> {{project.name}} </p> <!-- <span>{{project.code}}<span>  -->
	</div>
    </div>
    <div>
        <div> 
			<table>
					<tbody style="font-wieght:bold">					
						<tr>
							<td>&nbsp;&nbsp;&nbsp;Type of Project : {{project.project_type.name}}</td>
							
						</tr>
						<tr>
							<td>&nbsp;&nbsp;&nbsp;Planned Start Date : {{project.schedules.planned_start_date|date:"d-m-Y"|cut:"01-01-2000"|cut:"01-01-1900"}}</td>
							<td>&nbsp;&nbsp;&nbsp;Planned End Date : {{project.schedules.planned_end_date|date:"d-m-Y"|cut:"01-01-2000"|cut:"01-01-1900"}}</td>
						</tr>
						{% if project.ex_approval == 1 %}
						<tr><td colspan="2">&nbsp;&nbsp;&nbsp;<b>Project Code :  {{ project.code }}</b></td></tr>
						{% endif %}
					</tbody>
			</table>        
         </div>
        
    		
    </div>
</div>
<div style="clear:both"></div>
<br><br>
<div class="sub-menu">
    <div class="sub-menu-btn" id="mnuHome">
        <a href="/project/home/?ids={{project.id}}">Home</a>
    </div>
    {% if perms.tasks.add_task or perms.tasks.change_task or it_admin_user %}
        <div class="sub-menu-btn" id="mnuTask">
            <a href="/task/list/?pid={{project.id}}">Task</a>
        </div>
    {% endif %}
    
    {% if perms.milestone.add_milestone or perms.milestone.change_milestone %}
        <div class="sub-menu-btn" id="mnuMilestone">
            <a href="/milestone/list">Milestone</a>
        </div>
    {% endif %}
    {% if perms.projects.change_project %}
        <div class="sub-menu-btn1" id="mnuProject">
            <a href="/project/update/?ids={{project.id}}">Update Project</a>
        </div>
    {% endif %}
    {% if perms.projects.change_project %}
        <div class="sub-menu-btn1" id="mnuProjectBudget">
            <a href="/projectbudget/create/?pjt_id={{project.id}}">Project Budget</a>
        </div>
    {% endif %}
    {% if perms.projects.add_project %}
	<div class="sub-menu-btn1" id="mnuPrint">
            <a href="/project/printdetails/{{project.id}}/">Print Project details</a>
        </div>
    {% endif %}
</div>