project_management/milestone/urls.py
"""
    urls for milestone
"""
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('project_management.milestone',
    (r'^$', 'views.milestone_list'),
    (r'^list/$', 'views.milestone_list'),
    (r'^list/(?P<pageNo>\d+)/$', 'views.milestone_list'),
    url(r'^create/$', 'views.manage_milestone', name='create-milestone'),
    url(r'^update/(?P<id>\d+)/$', 'views.manage_milestone', name='update-milestone'),
    (r'^delete/$', 'views.milestone_delete')
)

project_management/urls.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import list_detail
from django.views.generic.simple import direct_to_template, redirect_to

from project_management.users.models import UserProfile
from project_management.users.views import login

from project_management.projectbudget.models import *
from project_management.projectbudget.budgetmasters import *

import os.path
import django_cron

admin.autodiscover()

try:
    django_cron.autodiscover()
except:
    pass

# for the calender(datepicker) widget
urlpatterns = patterns('', (r'^jsi18n/$',
    'project_management.i18nDate.javascript_catalog',
    {'packages': 'django.conf'}),)

js_info_dict = { 'packages': ('cui.translations',), }

urlpatterns += patterns('', (r'^django-jsi18n/$',
    'django.views.i18n.javascript_catalog', js_info_dict), )

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^login/$', login, {'template_name': 'login.html'}),
    (r'^comingsoon/$', direct_to_template, {'template': 'coming_soon.html'}),
    (r'^recentupdates/$',direct_to_template, {'template': 'Recent_updates.html'}),
    (r'^re-use/$', direct_to_template, {'template': 're-use.html'}),
    (r'^re-use/components/$', direct_to_template, {'template': 'Re-Use_Library.html'}),
    (r'^5GPal/$', direct_to_template, {'template': '5G-Pal.html'}),
    (r'^5GPal/Policies/$', direct_to_template, {'template': '5gpal_Policies.html'}),
    (r'^5GPal/FxCop_and_Rules/$', direct_to_template, {'template': '5gpal_FxCop_and_Rules.html'}),
    (r'^5GPal/Process-templates/$', direct_to_template, {'template': '5gpal__process-templates.html'}),
    (r'^Mindshare/', redirect_to, {'url': '/login/'}),
    (r'^logout/$', logout, {'template_name': 'logout.html'}),
    (r'^contacts/$', login_required(list_detail.object_list),
        {'queryset':UserProfile.objects.exclude(user__is_active = False).exclude(
        user__is_staff = True).order_by('user__username'),
        'template_name': 'contacts.html'}),
)

# to load the static data
#if settings.DEBUG:
urlpatterns += patterns('', (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': os.path.join(settings.PROJECT_ROOT, "media")}),)

urlpatterns += patterns('project_management.logs',
    (r'^Logs/', 'views.DisplayLog'),
    (r'^admin.ShowLog/', 'views.DisplayLogData'),
    (r'^GetLogDetail/', 'views.GetLog'),
)

urlpatterns += patterns('',
    (r'^user/', include('project_management.users.urls')),
    (r'^project/', include('project_management.projects.urls')),
    (r'^projectbudget/', include('project_management.projectbudget.urls')),
    (r'^alert/', include('project_management.alert.urls')),
    (r'^customer/', include('project_management.customer.urls')),
    (r'^task/', include('project_management.tasks.urls')),
    (r'^milestone/', include('project_management.milestone.urls')),
    (r'^businessunit/', include('project_management.business_unit.urls')),
    (r'^event/', include('project_management.notifications.urls')),
    (r'^announcement/', include('announcements.urls')),

    # (r'^client_visit_report/', include('project_management.client_visit_report.urls')),
    
    (r'^timesheet/', include('project_management.timesheet.urls')),
    (r'^timesheetnew/', include('project_management.timesheetnew.urls')),
    (r'^NewsLetter/', include('newsletter.urls')),
    (r'^conferenceroombooking/', include('project_management.conferenceroombooking.urls')),
    (r'^codereview/', include('project_management.code_review.urls', namespace="codereview")),
    #(r'^library/',include('project_management.library.urls')),
)

urlpatterns += patterns('project_management.notifications',
    (r'^MonthlyCalendar/$', 'eventviews.MonthlyCalendar'),
    (r'^WeeklyCalendar/$', 'eventviews.WeeklyCalendar'),
    (r'^DayCalendar/$', 'eventviews.DayCalendar'),
    (r'^previousyear/(?P<type>\w+)/', 'eventviews.previousyear'),
    (r'^nextyear/(?P<type>\w+)/', 'eventviews.nextyear'),
    (r'^previousmonth/', 'eventviews.previousmonth'),
    (r'^nextmonth/', 'eventviews.nextmonth'),
    (r'^nextday/', 'eventviews.nextday'),
    (r'^previousday/', 'eventviews.previousday'),
    (r'^nextweek/', 'eventviews.nextweek'),
    (r'^previousweek/', 'eventviews.previousweek'),
    (r'^Event/', 'eventviews.Events'),
    (r'^CreateEvent/', 'eventviews.Events'),
    (r'^SaveEvent/', 'eventviews.saveEvent'),
    (r'^Eventdelete/', 'eventviews.eventDelete'),
    (r'^UpdateEvent/', 'eventviews.updateEvent'),
    (r'^EventAccess/', 'eventviews.accessEvent'),
    (r'^GetStage/', 'eventviews.getStage'),
)

#  Program Task (Internal Tab) URL's
urlpatterns += patterns('project_management.projects',
    url(r'^prog_task_in_pg/$', direct_to_template, {"template": "prog_task_in_pg.html"}, name="prog_task_in_pg"),
    #(r'^UpdateProgramTask/', 'ProgTaskListsViews.program_task_update_pg'),
    #(r'^CreateProgramTask/', 'ProgTaskListsViews.createprogramtask'),
    #(r'^CreateContinueProgramTask/', 'ProgTaskListsViews.createandcontinueprogramtask'),
    #(r'^prog_task_up/', 'ProgTaskListsViews.program_task_update'),
)

urlpatterns += patterns('project_management.repository',
    (r'^repository/', 'views.RepositoryView'),
    (r'^repositoryUpload/', 'views.RepositoryUpload'),
)

urlpatterns += patterns('project_management.non_project_task',
    #(r'^CreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskView'),
    #(r'^GetProjectTasklists/', 'createMenuTaskViews.GetTasklists'),
    #(r'^GetProjectTasklistsResources/','createMenuTaskViews.GetTasklistsResources'),
    #(r'^SaveCreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskSave'),
    #(r'^SaveAndContinueCreateMenuTask/', 'createMenuTaskViews.CreateMenuTaskSaveAndContinue'),
)

urlpatterns += patterns('project_management.non_project_task.views',
    #(r'^NonProjectTaskList/', 'NonProjectTaskList'),
    #(r'^CreateNonProjectTask/', 'NonProjectTaskView'),
    #(r'^UpdateNonProjectTask/', 'NonProjectTaskView'),
    (r'^SaveNonProjectTask/', 'SaveNonProjectTask'),
    (r'^SaveAndContinueNonProjectTask/', 'SaveAndContinueNonProjectTask'),
    #(r'^NonProjectTaskdelete/', 'NonProjectTaskDelete'),
)

urlpatterns += patterns('project_management.Utility',
    (r'^GetPopUpDetails/', 'getPopUpDetails'),
)

urlpatterns += patterns('project_management.common_manager.views',
    (r'^MasterView/', 'MasterView'),
    (r'^MasterSave/', 'MasterSave'),
    (r'^MasterDelete/','MasterDelete'),
)

#urlpatterns = patterns('project_management.projectbudget.views',
 #                      (r'^projectbudget/$', 'projectbudget.views.cost'),
  #                    )

project_management/milestone/models.py
"""
    Milestone Models
"""

from django.db import models
from django.utils.translation import ugettext_lazy as _

class InvoiceTerms(models.Model):
    """
        Represents the invoice terms of the project
    """
    name = models.CharField(max_length = 120)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('Invoice Term')
        verbose_name_plural = _('Invoice Terms')

class Milestone(models.Model):
    """
        Represents the milestones related to the project
    """
    INVOICE = 'invoice'
    ENGINEERING = 'engineering'
    category_choices = ((INVOICE, 'invoice'), (ENGINEERING, 'engineering'))
    name = models.CharField(max_length = 120, verbose_name = _('milestone'))
    percentage = models.CharField(max_length= 10, null = True,
                    blank = True, verbose_name = _('percentage'))
    start_date = models.DateField(_('Invoice Start Date'), null = True,
                    blank = True)# Just start date.
    end_date = models.DateField(_('Invoice End Date'), null = True,
                    blank = True)
    invoice_terms = models.ForeignKey(InvoiceTerms, blank = True, null = True,
                                      verbose_name = _('Invoice Terms'))
    category = models.CharField(max_length = 16, choices = category_choices,
                                default = category_choices[0][0]) #TODO Replace with invoice.
    notes = models.TextField(null = True, blank = True, verbose_name=_('Notes'))
    cancel = models.BooleanField(default = False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('Milestone')
        verbose_name_plural = _('Milestones')

project_management/milestone/forms.py
"""
    Milestone forms
"""
from django import forms

from project_management.milestone.models import Milestone

DATE_INPUT_FORMAT = '%m-%d-%Y'
DATE_FIELD_ATTR = {'class':'vDateField'}

class EngineeringMilestoneForm(forms.ModelForm):
    '''
        form representing engineering milestone
    '''

    start_date = forms.DateField(input_formats = [DATE_INPUT_FORMAT],
        required = False, widget=forms.TextInput(attrs = DATE_FIELD_ATTR))

    end_date = forms.DateField(input_formats = [DATE_INPUT_FORMAT],
        required=False, widget=forms.TextInput(attrs = DATE_FIELD_ATTR))

    class Meta:
        model = Milestone
        fields = ['name', 'start_date', 'end_date', 'notes']

    def save(self, project, id, commit=True):
        milestone = super(EngineeringMilestoneForm, self).save(commit=False)
        milestone.category = Milestone.category_choices[1][1]
        if commit:
            milestone.save()
            if not id:
                project.milestone.add(milestone)
        return milestone

project_management/milestone/views.py
"""
    Milestone views
"""
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import list_detail
from django.db.models import Q

#from project_management.users.models import FiveGUser
from project_management.milestone.models import Milestone
from project_management.projects.models import Project
from project_management.milestone.forms import EngineeringMilestoneForm


def milestone_list(request, pageNo = 1):
    project_code = request.GET.get('pid', '')
    try:
        project = Project.objects.get(id = project_code)
    except:
        #TODO: very bad logic. remove project id from session.
        project = Project.objects.get(id = request.session['projectid'])
    query = Q()
    search_text = request.GET.get('search', '')
    if search_text:
        q = Q()
        for term in search_text.split():
            q = Q(name__icontains = term)
        query = query & q
    milestone_set = Milestone.objects.filter(query, project = project,
        category = Milestone.ENGINEERING)
    return list_detail.object_list(
        request,
        queryset = milestone_set,
        template_name = "milestone_list.html",
        template_object_name = "milestone",
        extra_context = {'project': project }
        )

@login_required
def milestone_delete(request):
    """
        delete milestones
    """
    milestone_ids = request.POST.getlist('milestone_pk')
    Milestone.objects.filter(pk__in = milestone_ids).delete()
    return HttpResponseRedirect(reverse(milestone_list))

@login_required
def manage_milestone(request, id = None):
    """
        create and modify milestones
    """
    milestone = None
    project_id = request.GET.get('pid', None)
    project = get_object_or_404(Project, code = project_id)
    if id:
        milestone = get_object_or_404(Milestone, pk = id)
    if request.method == 'POST':
        milestone_form = EngineeringMilestoneForm(request.POST,
                                instance = milestone)
        if milestone_form.is_valid():
            milestone_form.save(project = project, id = id)
            return HttpResponseRedirect(reverse(milestone_list))
    else:
        milestone_form = EngineeringMilestoneForm(instance = milestone)
    return render_to_response('milestone.html', {'form': milestone_form,
        'project': project}, context_instance = RequestContext(request))

project_management/repository/views.py
"""
    Repository Views
"""
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _

from project_management.logs.logger import CapturLog
from project_management.repository.fileform import FileUploadForm
from project_management.repository.models import RepositoryTags, Repository
from project_management.Utility import ChangeMode, Util

import os

actionMsg = {
    '': '',
     'Save': _('File Uploaded successfully'),
    'Uploadunsuccessful': _('Invalid File. Cannot be uploaded'),
    'MaxFilesize'           :_('Maximum filesize exceeded'),
    'ProjectInactive': _('Project is inactive. File Upload cannot be done.'),
    'FileSizeMsg':_('Maximum file size allowed is %sMb'),
    'Access Denied': _('Access Denied'),
    }

MODULE = 'repository'
THOUSAND = 1000

def get_program_details(request):
    programId = request.session.get('projectid', '')
    try:
        program = Project.objects.get(id = programId)
    except:
        program = None
    return program



def RepositoryView(request):
    userName = ''
    repositoryTags = RepositoryTags.objects.all()
    repositoryTagID = request.GET.get('tagID', '')
    filesize = (settings.MAX_FILE_SIZE / THOUSAND) / THOUSAND
    fileSizeMsg = actionMsg['FileSizeMsg'] % filesize
    msg = request.GET.get('msg', '')
    LoginData = request.session.get('LoginData', '')
    if LoginData != '':
        userName = LoginData['userName'][0]
    form = FileUploadForm()
    program = get_program_details(request)
    downloadpath = settings.MEDIA_URL
    if repositoryTagID != '':
        repository = Repository.objects.filter(program
            = program).filter(repositoryTag = repositoryTagID)
    else:
        repository = Repository.objects.filter(program = program)
    return render_to_response('Repository.html', {
        'userName': userName, 'downloadpath':downloadpath,
        'prog_to_up': program,'repositoryTags':repositoryTags,
        'msg': actionMsg[msg],'repositoryTagID':repositoryTagID,
        'templateForm': form, 'action': 'Update',
        'repository': repository, 'fileSizeMsg':fileSizeMsg },
        context_instance = RequestContext(request))


def RepositoryUpload(request):
    try:
        form = FileUploadForm(request.POST, request.FILES)
        msg = ''
        flg = 0
        repositoryTag = request.POST.get('repositoryTag', '0')
        if repositoryTag == '':
            repositoryTag = '0'
        if form.is_valid():
            program = get_program_details(request)
            uploadedFile = form.cleaned_data['fileUploaded']
            name = uploadedFile.name
            for each in settings.FILE_EXTENSIONS_TO_EXCLUDE:
                if name.__contains__(each):
                    flg = 1

            if uploadedFile._size > settings.MAX_FILE_SIZE:
                msg = 'MaxFilesize'
                CapturLog().LogData(request, 'Upload', MODULE, actionMsg[msg])
                return RepositoryView(request, msg)

            if flg != 1:
                fileUploaded = request.FILES['fileUploaded']
                check = 0
                ID = request.session.get('projectid', '')
                randomID = Util().Guid()
                repository = Repository.objects.create(fileID
                    = randomID, program_id = ID, repositoryTag_id = repositoryTag)
                filename = fileUploaded.name

                currentdir = settings.MEDIA_ROOT + '/all files/'
                ChangeMode(settings.MEDIA_ROOT)
                ChangeMode(currentdir)
                currentosdir = currentdir
                currentdir = os.listdir(currentdir)
                for each in currentdir:
                    if each == ID:
                        check = 1
                if(check != 1):
                    os.mkdir(currentosdir+ID)

                fd = open('%s/%s' % (currentosdir + ID, randomID + filename), 'wb')
                for chunk in fileUploaded.chunks():
                    fd.write(chunk)
                fd.close()

                filepath = 'all files/' + ID + '/'+randomID + filename if filename !=  '' else ''
                repository.fileUploaded = filepath
                repository.name = name
                repository.save()
                msg = 'Save'
                CapturLog().LogData(request, msg, MODULE, actionMsg[msg], repository)
                form = FileUploadForm()
            else:
                msg = 'Uploadunsuccessful'
                CapturLog().LogData(request, 'Save', MODULE, actionMsg[msg])
        else:
            CapturLog().LogData(request, 'Save', MODULE, actionMsg['Uploadunsuccessful'])
    except (RuntimeError, TypeError, NameError):
        errMessage = ''
        CapturLog().LogData(request, msg, MODULE, actionMsg[msg])

    if request.POST.get('fromHome','') == 'fromHome':
        return HttpResponseRedirect('/ProjectHome/?msg=' + msg)
    else:
        return HttpResponseRedirect('/repository/?msg=' + msg)

project_management/templates/templates/DayCalendar.html
{% extends "base.html" %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}
{% block title %} Daily Event Calendar {% endblock %} {% block programcontent %} {% endblock %}
{% block programmenu %}{% endblock %} {% block submenu %}{% endblock %} 
{% block taskmenus %}{% endblock %} 
{% block contentdata %}


{% url notifications.eventviews.nextyear 'day' as next_year %}
{% url notifications.eventviews.previousyear 'day' as previous_year %}
{% url notifications.eventviews.nextday as next_day %}
{% url notifications.eventviews.previousday as previous_day %}

<script language="JavaScript">
/*function init() 
 { 
 	document.getElementById('times').scrollTop = 400;
 	if (navigator.appName == "Netscape"){
 	document.getElementById('topLinks').style.width = "48%";
 	}
 	else{
 	document.getElementById('topLinks').style.width = "44%";
 	}
	
 };

if (navigator.appName == "Netscape")
{
  for Mozilla 
   if (document.addEventListener) 
   {
       document.addEventListener("DOMContentLoaded", init, false);
   }
}
else
{
 window.onload = init;
}   
*/
</script>
<style>
.year{font-weight: bold; font-size:21px;}
</style>

        <div class="wr-ar">
            <div class="program-hdr">
               
                <span class="header">Daily View</span>
            </div>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td style="text-align: center; vertical-align: middle;">
                        <label id="msg" class="Arial-12-maroon">
                        </label>
                    </td>
                </tr>
                <style>
                .calenderlink{padding-right: 10px; padding-top: 10px; width: 300px; }
                .form{ float: right }
                </style>
                <tr>
                    <td align="right"  valign="top" class="program-name-form-box" width="100%">
                    <div class="calenderlink">
                                <label>
                                    <a href="/DayCalendar/" style="color:Maroon"  >Day</a>
                                </label>
                            &nbsp;|&nbsp;
                                <label>
                                    <a href="/WeeklyCalendar/"  >Week</a>
                                </label>
                            &nbsp;|&nbsp;
                                <label>
                                    <a href="/MonthlyCalendar/" >Month</a>
                                </label>
                            &nbsp;
                            <div class="form">
                               <form name="Add_new" action="/Event/" method="GET">
                                   <input type="submit" name="button" id="SubmitEvent" value="Create Event" class="b1"/>
                               </form>
                            </div>
                    </div>
                </td>
                </tr>
            </table>
        
            <form name="dayCal" id="dayCal" action="/MonthlyCalendar/">
                        <div align="center"  style="padding-top: 15px; padding-bottom: 5px; padding-left: 15px;
                            padding-right: 15px; ">
                            <table cellspacing='0' cellpadding='0'  width='100%' style="border:2px solid #dbe6ed;">
     <tr class="link-line-bg" style=" width: 18px;border:2px solid #dbe6ed;">
         <td  class="previous" align="left" >            
             <a title="previous year" class="year" href="{{ previous_year }}"><span class="calendar-arrow">&lt;</span></a>
             <a class="menu-btn-link" title="previous day"  href="{{ previous_day }}"><span class="calendar-arrow">&lt;&lt;</span></a></td>
         <td  class="menu-btn-link" align="center" style="text-align: center; font-weight: bold;
             font-size:20px;">
             {{ monthyear }}</td>
         <td  class="next" align="right" style="width: 8%;">         
             <a class="menu-btn-link" title="next day" class="year" href="{{ next_day }}"><span class="calendar-arrow">&gt;&gt;</span></a>
            <a title="next year" style="text-align: center; font-weight: bold;font-size:21px; " href="{{ next_year }}"><span class="calendar-arrow">&gt;</span></a></td>
             
             </td>
     </tr>
                                <tr style="color: Maroon;border:2px solid #dbe6ed;" >
					<th style="width: 8%;"></th>
                                    {% for day in headers %}
                                    <th style="text-align:center;" >
                                         <a href="/Event/?selecteddate={{day}}" style=" color:Maroon;">{{ day|date:"l,d" }}</a></th>
                                    {% endfor %}<th style="width: 8%"></th>
                                </tr>
            </table>
            <div id="times" style="height:310px; overflow: auto;overflow-x:hidden;" width='100%'>
            <table cellspacing='0' cellpadding='0' style="border:2px solid #dbe6ed;" width='100%'>
				{% for times in timedata %}
				{% load tags %}				
   				
				
				<tr style="height: 25px;border:2px solid #dbe6ed;" >
				<td style="width: 8%;border:2px solid #dbe6ed;">
				{{times}}</td>	
				{% for key,value in monthdata.items %} 
                                {% ifequal times key %}
				<td colspan="2"   style="border:2px solid #dbe6ed;">
				{% tags value %}</td>
				{% endifequal %}					
				{% endfor %}		
                             </tr>
				{% endfor %}
				
                            </table></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}

project_management/templates/templates/create_conference_room.html
{% extends "base.html" %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block script %}
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}

{% block title %} Task {% endblock %}

{% block contentdata %}
    <style>
        form { padding: 10px; }
        .entry-form{ width: 100%; }
        .element{ width: 50%; min-height: 30px; float: left; }
        .label { width: 40%; float: left; }
        .field { width: 60%; float: left; }
        .SaveAndCancel{ width: 100%; clear: both; }
        input[type=text]{ width: 160px;}
        select{ width: 170px; }
        #id_notes{ width: 250px; height: 90px;}
    </style>

    <script>
    $(document).ready(function(){
    $('#cancel').click(function(){
            window.location.href = '{% url conferenceroombooking.views.manage_book_conference_room %}'
        });    
        
    });
    </script>

    <form id="conference_room_form" name="conference_room_form" action="" method="POST" />
        <div class="header">Create Conference Room</div>
        <br/>
        <br/>
        {% if messages %}
            {% for message in messages %}
                <div class="message {{ message.tags }}"><h4>{{ message }}</h4></div>
            {% endfor %}
        {% endif %}

        {{form.errors}}
        <div class="entry-form">
            {% for field in form %}
                <div class="element">
                    <div class="label">{{field.label_tag}}</div><div class="field">{{field}}</div>
                </div>
                
            {% endfor %}
        </div>

        <div class="SaveAndCancel">
            <input type="submit" id="save" name="save" value="save"/>
            <input type="button" id="cancel" name="cancel" value="cancel" />
            
        </div>
    </form>
{% endblock %}

project_management/templates/templates/milestone.html
{% extends "base.html" %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" title="standard-css1" />
    <link href="/static/css/forms.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block script %}
    <script type="application/javascript" src="/static/js/84.js"></script>
    <script type="application/javascript" src="/jsi18n/"></script>
    <script type="application/javascript" language="JavaScript" src="/static/js/calendar.js"></script>
    <script type="application/javascript" language="JavaScript" src="/static/js/core.js"></script>
    <script type="application/javascript" language="JavaScript" src="/static/js/admin/DateTimeShortcuts.js"></script>
    <script type="application/javascript" language="JavaScript" src="/static/js/Validation.js"></script>
    <script type="application/javascript" src="/static/js/jquery-1.3.2.min.js"></script>
{% endblock %}
{% block title %}   {% endblock %} 
{% block contentdata %}

{% url create-milestone as create_milestone_url %}
{% url projects.views.project_list as program_project_list %}
<script>
$(document).ready(function(){
    convertDate('id_start_date');
    convertDate('id_end_date');
    $('#id_start_date').attr('class', 'vDateField');
    $('#id_end_date').attr('class', 'vDateField');    
    });
</script>
<script type="application/javascript">
function saveMilestone(){
   if( !isBetweenDate(document.getElementById("id_start_date").value,document.getElementById("id_end_date").value)){
		alert ('End date occurs before the start date');
		document.getElementById('id_end_date').focus();
		return false;
    }    
    return true;
}
</script>
<style>
#id_notes { width: 500px; height: 100px; }
.content { padding : 20px; }
</style>
<form action="" id="stageform" name="stageform" method="POST">
    <noscript>this web page work best with javascript enabled browser</noscript>

   {% include 'project_menus.html'%} 

    <div class="header">
        Create Milestone
    </div>
    <center>{{ message }}</center>
    <div class="program-name-form-box content">
        <input type="hidden" id="redirection_url" name="redirection_url" />
        <table>
            {{form.as_table}}
            <tr>
                <td></td>
                <td><input type="submit" name="save" id="save" value="save" class="b1" onclick="return saveMilestone();" />
                <input type="button" name="cancel" id="cancel" value="cancel" class="b1" onclick="window.location.href='/milestone/'" />
                </td>
            </tr>
        </table>
    </div>
<form>
{% endblock %}